import '../styles/globals.css'
import Head from 'next/head'
import React from 'react'
import { Provider } from 'react-redux'
import store from '../redux/store'
import NavBar from '../components/NavBar'

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Provider store={store}>
          <Head>
              <title>E-commerce</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <NavBar />
          <div>
            
              <Component {...pageProps} />
            
          </div>
      </Provider>
    </div>
  )
}

export default MyApp
